name: Test pull request

on: [pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.SUPABASE_PRODUCTION_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.SUPABASE_PRODUCTION_PROJECT_ID }}

    defaults:
      run:
        working-directory: ./game

    steps:
      - uses: actions/checkout@v7
      - uses: supabase/setup-cli@v3
        with:
          version: 2.109.1
      - run: supabase link --project-ref $SUPABASE_PROJECT_ID
      - run: supabase db start
      - uses: pnpm/action-setup@v6
        with:
          version: 8.14.3
          run_install: true
      - run: pnpm gen:types
      - run: pnpm test
